# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1452b885f18ec714ff856e2267d1d88bd9e35bd1907d89cdd85209075fbbebbec2f79621d584de874fe8682bb09f4d37141c7ccd1e3b9980bb65f79dded1b14d
  facebook_app_id: 1097926690353498
  facebook_app_id: f14722f0836cb90bda1e317adca47dc8
test:
  secret_key_base: b1fe484fa14a0d73383b7a70408dd670114ca46b9c75f1120f67eb252dac8b6392f783bc292df512bdea1ec5caf81d851cfab556cb0246c2126ea6d96f69a6c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
